version: '2'

services:
    engine:
        build:
            context: ./docker/engine/
            args:
                host_uid: 1000
                host_gid: 1000
        restart: always
        ports:
            - 443:443
        volumes:
            - .:/home/all-my-statuses:rw
        working_dir: /home/all-my-statuses
